version: '3.6'
services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=restaurant
    ports:
      - "3306:3306"
    expose:
      - 3306

  authentication:
    image: "sajadkh/authentication:latest"
    container_name: Authentication
    depends_on:
      - mysql
    command: sh -c "./wait && ./start.sh"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "8000:8000"
    expose:
      - 8000

  restaurant:
    image: "sajadkh/restaurant:latest"
    container_name: Restaurant
    depends_on:
      - mysql
    command: sh -c "./wait && ./start.sh"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "8001:8001"
    expose:
      - 8001

  Customer:
    image: "sajadkh/customer:latest"
    container_name: Customer
    depends_on:
      - mysql
    command: sh -c "./wait && ./start.sh"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "8002:8002"
    expose:
      - 8002